--CURSOR DIEMTRUNGBINH
DECLARE CURSORDIEMTRUNGBINH CURSOR 
FOR SELECT MAHS, HOCKY FROM XEPLOAI

OPEN CURSORDIEMTRUNGBINH
DECLARE @MAHS CHAR(10), @HOCKY CHAR (10)

FETCH NEXT FROM CURSORDIEMTRUNGBINH INTO @MAHS, @HOCKY
WHILE @@FETCH_STATUS = 0
BEGIN 
	DECLARE @DIEM1 FLOAT, @DIEM2 FLOAT , @DIEM3 FLOAT, @DIEM4 FLOAT, @DIEMTB FLOAT
	--DIEM THI MIENG
	SELECT @DIEM1 = DIEMTHIMIENG
	FROM KETQUA
	WHERE MAHS = @MAHS AND HOCKY = @HOCKY
	--DIEM 15P
	SELECT @DIEM2 = DIEMTHI15P
	FROM KETQUA
	WHERE MAHS = @MAHS AND HOCKY = @HOCKY
	--DIEM THI 1 TIET
	SELECT @DIEM3 = DIEMTHI1TIET
	FROM KETQUA
	WHERE MAHS = @MAHS AND HOCKY = @HOCKY
	--DIEM THI HOC KY
	SELECT @DIEM4 = DIEMTHIHOCKY
	FROM KETQUA
	WHERE MAHS = @MAHS AND HOCKY = @HOCKY
	--DIEM TRUNG BINH
	SET @DIEMTB = (@DIEM1*0.1 + @DIEM2*0.1 + @DIEM3*0.3 + @DIEM4*0.5)
	FETCH NEXT FROM CURSORDIEMTRUNGBINH INTO @MAHS, @HOCKY
END
CLOSE CURSORDIEMTRUNGBINH
DEALLOCATE CURSORDIEMTRUNGBINH

--PHÂN QUYỀN 
SP_ADDROLE 'GIAOVIEN'
SP_ADDROLE 'HOCSINH'

GRANT SELECT , INSERT , UPDATE 
ON KETQUA TO GIAOVIEN

GRANT SELECT , INSERT , UPDATE
ON LOP TO GIAOVIEN

GRANT SELECT 
ON KETQUA TO HOCSINH



>>>>>>> e3429896cb7828c629905d94936901f46b60b3f0
