-- In danh sách học sinh
ALTER PROC IN_DANH_SACH_HOC_SINH
AS
BEGIN
	SELECT MAHS, HOTEN, (SELECT TENLOP FROM LOP WHERE HOCSINH.MALOP = LOP.MALOP) AS TEN_LOP, GIOITNH AS GIOI_TINH, NGAYSINH, DIENTHOAI, DIACHI FROM HOCSINH
END
EXEC IN_DANH_SACH_HOC_SINH

CREATE TABLE THOIKHOABIEUGIAOVIEN
(	
	HOCKY CHAR(10),
	MAGV CHAR(10),
	TIET CHAR(10),
	THU_2 CHAR(10),
	THU_3 CHAR(10),
	THU_4 CHAR(10),
	THU_5 CHAR(10),
	THU_6 CHAR(10),
	THU_7 CHAR(10),
	CONSTRAINT PK_MAGV_TKB FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV),
)

INSERT INTO THOIKHOABIEUGIAOVIEN (HOCKY,MAGV,TIET,THU_2,THU_3,THU_4,THU_5,THU_6,THU_7)
VALUES
('1','GV00001','Tiet 1','10/1','10/2','10/3',NULL, '10/1','10/2'),
('1','GV00001','Tiet 2','10/1','10/2','10/3',NULL, '10/1','10/2'),
('1','GV00001','Tiet 3','10/3',NULL,NULL,NULL, NULL,NULL),
('1','GV00001','Tiet 4','10/3',NULL,NULL,NULL, NULL,NULL),
('1','GV00001','Tiet 5',NULL,NULL,NULL, NULL,NULL,NULL)


-- In danh sách các lơp giáo viên dạy
CREATE PROC IN_CAC_LOP_GIAO_VIEN_DAY @MAGV CHAR(10)
AS
BEGIN
	SELECT TIET,THU_2,THU_3,THU_4,THU_5,THU_6,THU_7 FROM THOIKHOABIEUGIAOVIEN WHERE MAGV=@MAGV
END
EXEC IN_CAC_LOP_GIAO_VIEN_DAY 'GV00001'
CREATE TABLE THOIKHOABIEUHOCSINH
(	
	HOCKY CHAR(10),
	MAHS CHAR(10),
	TIET CHAR(10),
	THU_2 CHAR(10),
	THU_3 CHAR(10),
	THU_4 CHAR(10),
	THU_5 CHAR(10),
	THU_6 CHAR(10),
	THU_7 CHAR(10),
	CONSTRAINT PK_MAHS_TKB FOREIGN KEY(MAHS) REFERENCES HOCSINH(MAHS)
)
INSERT INTO THOIKHOABIEUHOCSINH (HOCKY,MAHS,TIET,THU_2,THU_3,THU_4,THU_5,THU_6,THU_7)
VALUES
('1','10HS00001','Tiet 1','Toan','Ngu van','Tieng Anh','Toan', 'Tieng Phap','Tin hoc'),
('1','10HS00001','Tiet 2','Toan','Ngu van','Tieng Anh','Vat li', 'Tieng Phap','Tin hoc'),
('1','10HS00001','Tiet 3','Dia','Tin hoc','Lich su','Vat li', 'Hoa hoc','Tin hoc'),
('1','10HS00001','Tiet 4','Dia','Tin hoc','Lich su','Ngu van','The duc','Van hoc'),
('1','10HS00001','Tiet 5','Chao co','GDCD','Toan', 'Hoa hoc','The duc','SHCN')
SELECT *FROM THOIKHOABIEUHOCSINH

CREATE PROC IN_TKB_HOCSINH @MAHS CHAR(10)
AS
BEGIN
	SELECT TIET, THU_2,THU_3,THU_4,THU_5,THU_6,THU_7 FROM THOIKHOABIEUHOCSINH WHERE MAHS=@MAHS
END
EXEC IN_TKB_HOCSINH '10HS00001'

-- PROC DANG NHAP
INSERT INTO TAIKHOAN(LOAITK,TENDANGNHAP,MATKHAU)
VALUES ('HT','admin','admin')

CREATE PROC DANG_NHAP @LOAITK CHAR(20),@TENDANGNHAP CHAR(10), @MATKHAU CHAR(16)
AS
BEGIN
	IF (@LOAITK='HT') SELECT*FROM TAIKHOAN WHERE TENDANGNHAP= @TENDANGNHAP and MATKHAU= @MATKHAU
	ELSE IF(@LOAITK='GV') SELECT *FROM GIAOVIEN WHERE MAGV= @TENDANGNHAP AND MATKHAU=@MATKHAU
	ELSE SELECT *FROM HOCSINH WHERE MAHS =@TENDANGNHAP AND MATKHAU=@MATKHAU
END
EXEC DANG_NHAP 'HS','10HS00001','@Abc123'
UPDATE HOCSINH SET MATKHAU='@Abc123'
UPDATE GIAOVIEN SET MATKHAU='@Abc123'
