--1. Cập nhật sĩ số 
CREATE TRIGGER CAPNHAT_SISO
ON HOCSINH
AFTER DELETE, INSERT, UPDATE
AS
BEGIN
	UPDATE LOP
	SET SISO = (SELECT COUNT(*) FROM HOCSINH WHERE MALOP = LOP.MALOP)
	WHERE MALOP IN (SELECT DISTINCT MALOP FROM INSERTED)
END
GO
--2. Cập nhật thông tin tài khoản đăng nhập
--HS
CREATE TRIGGER CAPNHAP_TK_HS
ON HOCSINH
AFTER INSERT, UPDATE
AS
BEGIN
    -- Xóa các dòng trong TAIKHOAN có TENDANGNHAP nằm trong danh sách dòng INSERTED
    DELETE FROM TAIKHOAN WHERE TENDANGNHAP IN (SELECT MAHS FROM INSERTED);
-- Thêm các dòng mới từ INSERTED vào bảng TAIKHOAN
    INSERT INTO TAIKHOAN (LOAITK, TENDANGNHAP, MATKHAU)
    SELECT 'HS', MAHS, CONVERT(VARCHAR(10), NGAYSINH, 103) FROM INSERTED;
END
GO
--GV
CREATE TRIGGER CAPNHAP_TK_GV
ON GIAOVIEN
AFTER INSERT, UPDATE
AS
BEGIN
    -- Xóa các dòng trong TAIKHOAN có TENDANGNHAP nằm trong danh sách dòng INSERTED
    DELETE FROM TAIKHOAN WHERE TENDANGNHAP IN (SELECT MAGV FROM INSERTED);
    
    -- Thêm các dòng mới từ INSERTED vào bảng TAIKHOAN
    INSERT INTO TAIKHOAN (LOAITK, TENDANGNHAP, MATKHAU)
    SELECT 'GV', MAGV, CONVERT(VARCHAR(10), NGAYSINH, 103) FROM INSERTED;
END
GO
--3. Check thông tin nhập điểm thi (0<= DIEM <=10)
CREATE TRIGGER CHECK_DIEM
ON KETQUA
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS(	
		SELECT 1
		FROM INSERTED
		WHERE (DIEMTHIMIENG NOT BETWEEN 0 AND 10) 
			OR (DIEMTHI15P NOT BETWEEN 0 AND 10)
			OR (DIEMTHI1TIET NOT BETWEEN 0 AND 10)
			OR (DIEMTHIHOCKY BETWEEN 0 AND 10)
	)
	BEGIN
		RAISERROR(N'ĐIỂM THI PHẢI NẰM TRONG KHOẢNG 0 -> 10.', 16, 1);
		ROLLBACK TRANSACTION;
		RETURN;
	END
END
GO

--4. Check Họ và Tên đúng với chuẩn, không chứa các kí tự đặc biệt
--GV
CREATE TRIGGER CHECK_TENHO_GV
ON GIAOVIEN
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM INSERTED
		WHERE PATINDEX('%[^a-zA-Z]%', HOTEN) < 0
	)
	BEGIN
		RAISERROR(N'TÊN CỦA GIÁO VIÊN CHỨA KÍ TỰ ĐẶC BIỆT, VUI LÒNG KIỂM TRA LẠI.', 16, 1);
		ROLLBACK TRANSACTION;
		RETURN;
	END
END
GO
--HS
CREATE TRIGGER CHECK_TENHO_HS
ON HOCSINH
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM INSERTED
		WHERE PATINDEX('%[^a-zA-Z]%', HOTEN) < 0
	)
	BEGIN
		RAISERROR(N'TÊN CỦA HỌC SINH CHỨA KÍ TỰ ĐẶC BIỆT, VUI LÒNG KIỂM TRA LẠI.', 16, 1);
		ROLLBACK TRANSACTION;
		RETURN;
	END
END
GO
--5. Kiểm tra ngày sinh của học sinh, giáo viên phải trước ngày hiện tại 
--HS
CREATE TRIGGER CHECKNGAYSINH_HS
ON HOCSINH
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT 1 FROM INSERTED WHERE NGAYSINH > GETDATE())
	BEGIN
		RAISERROR('NGAY SINH PHAI BE HON NGAY HIEN TAI', 16, 1);
		ROLLBACK TRANSACTION;
		RETURN;
	END
END
GO
--GV
CREATE TRIGGER CHECKNGAYSINH_GV
ON GIAOVIEN
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT 1 FROM INSERTED WHERE NGAYSINH > GETDATE())
	BEGIN
		RAISERROR('NGAY SINH PHAI BE HON NGAY HIEN TAI', 16, 1);
		ROLLBACK TRANSACTION;
		RETURN;
	END
END
GO

